export type Resource = {
	translation: {
		'native-name': string;
		'journey-planner-title': string;
		'departures-title': string;
		'settings-title': string;
		'language-select-label': string;
		'no-options': string;
		'loading': string;
		'theme-select-label': string;
		'theme-light': string;
		'theme-dark': string;
		'from-label': string;
		'to-label': string;
		'favorites-and-recents-label': string;
		'show-departures': string;
		'login-label': string;
		'logout-label': string;
		'authenticated-as': string;
		'clear-label': string;
		'minutes-label': string;
		'now-label': string;
		'no-departures-label': string;
		'config-label': string;
		'travel-at-question': string;
		'travel-now': string;
		'choose-arrival-time': string;
		'choose-departure-time': string;
		'choose-date': string;
		'choose-time': string;
		'track-designation-label': string;
		'position-designation-label': string;
		'transfer': string;
		'walk-to': string;
	};
};
